### env config ###

image: Visual Studio 2015

### build config ###
version: 0.7.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: RelWithDebInfo
build:
  project: build\Odamex.sln
  verbosity: minimal
before_build:
  - ps: .\appveyor_before_build.ps1
after_build:
  - ps: .\appveyor_after_build.ps1

### artifacts config ###

artifacts:
  - path: odamex.zip
  - path: odasrv.zip